name: Check Commit changes/updates

on:
  push:
    branches:
      - main

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pyflakes
      run: pip install pyflakes

    - name: Run pyflakes
      run: pyflakes app.py
